name: Build

on:
  workflow_dispatch:
  push:
    branches: [master]
    tags:
      - v*
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v5
      - uses: Swatinem/rust-cache@v2
      - name: Install Dependencies
        run: sudo apt install libunwind-dev
        if: runner.os == 'Linux'
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Build
        run: cargo build --release --verbose --examples
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install optional numpy dependency
        run: pip install numpy>=2
      - name: Test
        id: test
        continue-on-error: true
        run: cargo test --release
      - name: Test (retry#1)
        id: test1
        run: cargo test --release
        if: steps.test.outcome=='failure'
        continue-on-error: true
      - name: Test (retry#2)
        run: cargo test --release
        if: steps.test1.outcome=='failure'
      - name: Build Wheel
        run: |
          pip install --upgrade maturin
          maturin build --release -o dist --all-features
        if: runner.os == 'Windows'
      - name: Build Wheel - universal2
        env:
          DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
          SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
          MACOSX_DEPLOYMENT_TARGET: 10.9
        run: |
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin
          pip install --upgrade maturin
          maturin build --release -o dist
          maturin build --release -o dist --target universal2-apple-darwin
        if: matrix.os == 'macos-latest'
      - name: Rename Wheels
        run: |
          python3 -c "import shutil; import glob; wheels = glob.glob('dist/*.whl'); [shutil.move(wheel, wheel.replace('py3', 'py2.py3')) for wheel in wheels if 'py2' not in wheel]"
        if: runner.os != 'Linux'
      - name: Upload Windows Wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-windows
          path: dist
        if: runner.os == 'Windows'
